### ISSUE TITLE
make select scene

### ISSUE THREAD

**Issue by alphaneet** [alphaneet/suparobo-engine#34]
# specs
- Stage Select Scene -> Deck Select Scene -> Game Scene
- Common Deck Class is extracted form Deck  Make Scene
- Deck Select Scene is created using Common Deck Class.
## ja lol
- まずマップエディタを使って、ボードを三つぐらい作る
- それぞれのチャンピオン用を使用したデッキ or ミニオン選択はランダムにする
- デッキ選択シーンは、デッキ作成画面のレイアウトを変更して使用する。

**Comment by alphaneet** [comment]
https://github.com/alphaneet/suparobo-engine/commit/b1ee4bc8bfde5840ac0a2f9a77452055d
http://twitpic.com/8eshat
http://twitpic.com/8esi1j

**Comment by xuwei-k** [comment]
githubのmarkdownは( Readme.md とか、こういうissueのcommentとか wiki とか) 
こうやって↓画像貼れますよ、っていうプチ情報

![ステージ選択画面](http://s1-03.twitpicproxy.com/photos/full/508572821.png)
![デッキ選択画面](http://s1-02.twitpicproxy.com/photos/full/508573783.png)

**Comment by alphaneet** [comment]
ぬおおおおおおお！！！！！
またひとつ賢くなったぞおおお！！！！！！
ありがとうございます！！！！！

**Comment by xuwei-k** [comment]
みんな意外と知らないですよね
https://twitter.com/#!/xuwei_k/status/104851359827898368

**Comment by alphaneet** [comment]
Jesus Christ!!!!!!
